baseURL = "https://e5-ssd.netlify.app/"
languageCode = "en-us"
title = "Passave"
theme = "hugo-xmin"

# theme = "hugo-bare-min-theme"
# [module]
#   [[module.imports]]
#     path = "github.com/kaushalmodi/hugo-bare-min-theme"

